apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pa-service.fullname" . }}
  labels:
    {{- include "pa-service.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.springProfilesActive | quote }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
